### ISSUE TITLE
Readme.MD Missing

### ISSUE THREAD

**Issue by levalencia** [jerriep/WebApiPaging#1]
Hello Jerrie

I just used your code and works perfectly fine for us, however the webapi paging has 4 different ways to page, but its not clear to me the difference amongsta all those methods, can you please share with me when to use which, or whats the difference between all of them?

I suggest a Readme.MD for this project too :)

thanks a lot

**Comment by jerriep** [comment]
@levalencia See this:
http://www.jerriepelser.com/blog/tags/aspnet-web-api

Look for the posts starting with "Paging in ASP.NET Web API: "
